company = input()
address = input()
phone = input()
fax = input()
website = input()
manager_first_name = input()
manager_last_name = input()
manager_age = input()
manager_phone = input()

print(company)
print(f"Address: {address}")
print(f"Tel. {phone}")
print(f"Fax: {fax}")
print(f"Website: {website}")
print(f"Manager: {manager_first_name} {manager_last_name} (age: {manager_age}, tel. +359 2 981 981)")
